[package]
name = "goat"
version = "0.1.0"
edition = "2024"

[lib]
name = "goat_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-shell = "2"
tauri-plugin-global-shortcut = "2"
tauri-plugin-autostart = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
xcap = "0.9.8"
ort = "2.0.0-rc.13"
ct2rs = "0.10.1"
